#!/usr/bin/env bash
# Generate docs/DOCS_INDEX.md from doc frontmatter across all categories.
#
# Usage: bash scripts/generate-docs-index.sh
#
# Extracts YAML frontmatter from all docs/*/**/*.md and produces
# a compact markdown table for on-demand agent reading.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
DOCS_DIR="$REPO_ROOT/docs"
OUTPUT="$REPO_ROOT/docs/DOCS_INDEX.md"

if [[ ! -d "$DOCS_DIR" ]]; then
  echo "No docs directory at $DOCS_DIR — skipping"
  exit 0
fi

# Extract a frontmatter field value from between --- markers.
# Handles single-line values and multi-line YAML block scalars (> and |).
get_field() {
  local file="$1" key="$2"
  local frontmatter value
  frontmatter=$(sed -n '/^---$/,/^---$/p' "$file")
  value=$(printf '%s\n' "$frontmatter" | grep "^${key}:" | head -1 | sed "s/^${key}:[[:space:]]*//" | sed 's/^"//;s/"$//' | tr -d '\r') || true
  # If value is a YAML block scalar indicator (> or |), read indented continuation lines
  if [[ "$value" == ">" || "$value" == "|" || "$value" == ">-" || "$value" == "|-" ]]; then
    value=$(printf '%s\n' "$frontmatter" | sed -n "/^${key}:/,/^[^ ]/p" | tail -n +2 | grep '^  ' | sed 's/^  //' | tr '\n' ' ' | sed 's/[[:space:]]*$//')
  fi
  printf '%s' "$value"
}

# Escape pipe characters so they don't break the markdown table
escape_pipes() {
  printf '%s' "$1" | sed 's/|/\\|/g'
}

# Infer category from parent directory name (e.g., docs/design/foo.md → design)
get_category() {
  local file="$1"
  local relpath="${file#"$DOCS_DIR"/}"
  echo "$relpath" | cut -d'/' -f1
}

# Collect all docs
ENTRIES=""
COUNT=0
MISSING=0
SKIPPED=0

while IFS= read -r filepath; do
  [[ "$filepath" == "$OUTPUT" ]] && continue
  title=$(get_field "$filepath" "title")
  if [[ -z "$title" ]]; then
    MISSING=$((MISSING + 1))
    echo "WARNING: missing frontmatter: ${filepath#"$REPO_ROOT"/}" >&2
    continue
  fi

  status=$(get_field "$filepath" "status")

  # Skip superseded docs — their guidance is replaced by another doc
  if [[ "$status" == "superseded" ]]; then
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  number=$(get_field "$filepath" "number")
  category=$(get_field "$filepath" "category")
  if [[ -z "$category" ]]; then
    category=$(get_category "$filepath")
  fi
  description=$(get_field "$filepath" "description")
  last_modified=$(get_field "$filepath" "last_modified")
  relpath="${filepath#"$REPO_ROOT"/}"

  # Fall back to extracting number from filename if frontmatter lacks it
  if [[ -z "$number" ]]; then
    basename_part=$(basename "$filepath")
    number=$(echo "$basename_part" | grep -oE '^[0-9]+' || true)
  fi

  ENTRIES="${ENTRIES}| ${category} | ${number} | ${status} | $(escape_pipes "$title") | $(escape_pipes "$description") | ${last_modified} | [${number:-link}](${relpath}) |
"
  COUNT=$((COUNT + 1))
done < <(find "$DOCS_DIR" -mindepth 2 -name '*.md' -type f | sort)

if [[ $COUNT -eq 0 ]]; then
  echo "No docs with frontmatter found — skipping"
  exit 0
fi

# Generate the index
mkdir -p "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<EOF
# Documentation Index

> Auto-generated by ship plugin (scripts/generate-docs-index.sh). Do not edit manually.

| Category | # | Status | Name | Description | Last Modified | Path |
|----------|---|--------|------|-------------|---------------|------|
${ENTRIES}
EOF

echo "Generated $OUTPUT with $COUNT entries"
[[ $SKIPPED -gt 0 ]] && echo "Skipped $SKIPPED superseded doc(s)" || true
[[ $MISSING -gt 0 ]] && echo "WARNING: $MISSING doc(s) missing frontmatter (not included)" || true
